### ISSUE TITLE
Ideas for wrapper script that loads gems without bundler?

### ISSUE THREAD

**Issue by drnic** [phusion/traveling-ruby#26]
I'm having an issue where the bin I'm running isn't expecting to be run under bundler and it doesn't clean the env before it spawns more processes.

Thoughts on how to write a wrapper script that invokes a bin without `-rbundler/setup`?

**Comment by FooBarWidget** [comment]
Can I assume that this issue is solved? I'm closing this issue unless I hear from you.

**Comment by drnic** [comment]
No. I have to fork the problem gem and constantly upgrade the fork to cut new releases.

**Comment by FooBarWidget** [comment]
Try this.

In your wrapper script:

    exec "$SELFDIR/lib/ruby/bin/ruby" -rbundler/setup -r"$SELFDIR/lib/undo_bundler" $SELFDIR/lib/vendor/ruby/2.1.0/bin/bosh $@

In lib/undo_bundler.rb:

    clean_env = Bundler.with_clean_env do
      ENV.to_hash.dup
    end
    ENV.replace(clean_env)

**Comment by FooBarWidget** [comment]
Did that help?

**Comment by JoshCheek** [comment]
You could invoke that binary without Bundler loaded. You just have to set the `$LOAD_PATH` correctly for it.

Here is an example where it executes the process without Bundler loaded, but which has access to all the libs it normally would. That process's children do not have Bundler loaded, and are not affected by the parent process's `$LOAD_PATH`.

```ruby
# Run this someplace there is a Bundler repository
Dir.chdir '/Users/josh/code/seeing_is_believing'

require 'open3'
require 'tmpdir'
require 'bundler/setup'

Dir.mktmpdir do |tmpdir|
  # Make a Ruby executable that shows info about the environment Bundler normally sets
  binpath = File.join tmpdir, 'show_interesting_shit.rb'
  File.write(binpath, <<-PROGRAM)
    indentation = ' ' * ARGV[0].to_i
    puts "\#{indentation}ENV['RUBYOPT']     # => \#{ENV['RUBYOPT'].inspect}"
    puts "\#{indentation}$LOAD_PATH.count   # => \#{$LOAD_PATH.count}"
    puts "\#{indentation}defined?(Bundler)  # => \#{defined?(Bundler).inspect}"

    puts "", "Child environment:"
    program_without_child = File.read(__FILE__).lines.take(__LINE__ - 2).join("")
    system 'ruby', '-e', program_without_child, '2'
  PROGRAM

  # Get paths to the gems Bundler normally makes available
  lib_paths = Bundler.load.specs.sort_by(&:name).map(&:full_gem_path)

  # Command to run Ruby with those libs available, but not propagated to child processes
  ruby_command = [
    'ruby',
    *lib_paths.flat_map { |path| ['-I', path] },
    '-S',
  ]

  # Run the binary without all the Bundler hijacking.
  # It should work b/c we're fixing the $LOAD_PATH,
  # but b/c we aren't messing with env vars, subprocesses will not be affected.
  Bundler.with_original_env do
    system(*ruby_command, binpath)
  end
end

# >> ENV['RUBYOPT']     # => ""
# >> $LOAD_PATH.count   # => 32
# >> defined?(Bundler)  # => nil
# >> 
# >> Child environment:
# >>   ENV['RUBYOPT']     # => ""
# >>   $LOAD_PATH.count   # => 9
# >>   defined?(Bundler)  # => nil
```

**Comment by JoshCheek** [comment]
Oh. That's not quite right, actually, you should go with `full_require_paths`, not `full_gem_path`. ie I have a [rake task](https://github.com/JoshCheek/seeing_is_believing/blob/a8904bf3030d8a9b29c131a862edbb50369d19bb/Rakefile#L27):

```ruby
sh 'ruby', '--disable-gem', *Bundler.load.specs.flat_map(&:full_require_paths).flat_map { |p| ['-I', p ] }, '-S', 'bundle/bin/rspec'
```
