### ISSUE TITLE
Install xz-5.0.7.tar.bz2 --- The requested URL returned error: 410 Gone

### ISSUE THREAD

**Issue by OhCoder** [phusion/traveling-ruby#27]
Under the OS X, run 'make' command. 
when I install "http://fossies.org/linux/misc/xz-5.0.7.tar.bz2", I found the request returned error: 410 Gone.

![screen shot 2015-01-03 at 22 05 12](https://cloud.githubusercontent.com/assets/890676/5602613/a7f00860-9394-11e4-924e-8caeb5d4fd0a.png)

Access the website, I found the file version updated to "http://fossies.org/linux/misc/xz-5.0.8.tar.gz/".

**Comment by FooBarWidget** [comment]
Looks like they removed older versions. :(

**Comment by etdsoft** [comment]
It seems like the official site keeps a few versions?

http://tukaani.org/xz/

http://tukaani.org/xz/xz-5.0.8.tar.gz
http://tukaani.org/xz/xz-5.0.7.tar.gz
http://tukaani.org/xz/xz-5.0.6.tar.gz

All seem to be working.
