### ISSUE TITLE
ruby 2.2.0

### ISSUE THREAD

**Issue by bradleyd** [phusion/traveling-ruby#28]
Any ETA on ruby 2.2.0 binary?

Thanks!

**Comment by FooBarWidget** [comment]
No such plans at the moment. Is there any specific reason why you want to use 2.2?

**Comment by bradleyd** [comment]
Yeah, we have a long running daemon that handles memory bloat better with
the changes in 2.2.

Thanks for the quick response.

**Comment by FooBarWidget** [comment]
All right, I'll put it on the roadmap, but getting Passenger 5 released is our main priority for now.

**Comment by bradleyd** [comment]
I totally understand.  Thanks for your time.

**Comment by FooBarWidget** [comment]
Upgrading to 2.2 is too major of a change for the next version, so I'll schedule it for the version after the next.

**Comment by bradleyd** [comment]
@FooBarWidget thanks for the update.

**Comment by FooBarWidget** [comment]
Implemented in the `next` branch. Will be part of the next release.

**Comment by FooBarWidget** [comment]
Traveling Ruby 20150210 is now released. Both 2.1.5 and 2.2.0 are supported.
