### ISSUE TITLE
Adding RedCloth

### ISSUE THREAD

**Issue by etdsoft** [phusion/traveling-ruby#29]
Hi  there,

Just trying to contribute a packaged version of RedCloth (following up from [here](https://github.com/phusion/traveling-ruby/issues/6#issuecomment-68262407)). Running OSX.

This is what I did:

1. Clone the repo
2. Added `gem 'RedCloth'` to `./shared/Gemfile`
3. Updated the reference to XZ library `XZ_VERSION=5.0.8` in `./osx/setup-runtime`
4. Ran

```bash
$ cd osx/
$ make
```

I see the:

```
Postprocessing build output...
------------------------------------------
....
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Installing RedCloth 4.2.9
Installing bcrypt 3.1.9
```

Which seems to run fine. And the process ends with

```
Packaging Ruby...
------------------------------------------
+ tar -cf traveling-ruby-20141224-2.1.5-osx.tar.gz.tmp -C output --exclude include/* --exclude lib/ruby/gems/2.1.0/extensions/* --exclude lib/ruby/gems/2.1.0/gems/* --exclude lib/ruby/gems/2.1.0/specifications/* .
+ tar -rf traveling-ruby-20141224-2.1.5-osx.tar.gz.tmp -C output ./lib/ruby/gems/2.1.0/gems/bundler-1.7.3 ./lib/ruby/gems/2.1.0/specifications/bundler-1.7.3.gemspec ./lib/ruby/gems/2.1.0/specifications/default
+ gzip --best --no-name -c traveling-ruby-20141224-2.1.5-osx.tar.gz.tmp > traveling-ruby-20141224-2.1.5-osx.tar.gz
+ rm traveling-ruby-20141224-2.1.5-osx.tar.gz.tmp
./package -E traveling-ruby-gems-20141224-2.1.5-osx output

Packaging gem native extensions...
------------------------------------------
There are no gems with native extensions.
```

Does this mean it worked? What's next?

**Comment by FooBarWidget** [comment]
Yes, looks easy enough. I'm currently preoccupied with Passenger 5 and other things but I'll put this on the roadmap.

**Comment by FooBarWidget** [comment]
Also, issue #27 needs to be fixed first. We need to find some kind of archive server that contains all xz releases, not just the latest one.

**Comment by etdsoft** [comment]
Is there something I can do to help? Would submitting a pull request work?

I'm happy to try the build on a Linux environment too.

**Comment by FooBarWidget** [comment]
Yes a pull request to fix #27 would help. Please also feel free to add redcloth to the Gemfile, and to update the changelog file accordingly.

**Comment by etdsoft** [comment]
I'm not sure I'm doing this right:

```
$ ./package -E traveling-ruby-gems-20141224-2.1.5-osx output

Packaging gem native extensions...
------------------------------------------
There are no gems with native extensions.
```
Shouldn't the compiled gems end somewhere in the `GEM_DIR := traveling-ruby-gems-$(VERSION)-$(RUBY_VERSION)-osx` folder?

I do get a `traveling-ruby-20141224-2.1.5-osx.tar.gz` but nothing else.

**Comment by FooBarWidget** [comment]
Yes, but did you run the build script before that? Each script has exact one job. `build` builds the binaries and stores them in an output directory. `package` packages relevant files in the output directory into package files.

**Comment by etdsoft** [comment]
I did run `make` (see top of the thread), which does the `./package` step as part of it, and since it didn't seem to produce anything, I also run the `./package` script and again nothing.

The output of `./build runtime output`: http://pastie.org/9818693#792

Around line 792:

```
Resolving dependencies...
Using RedCloth 4.2.9
```

**Comment by FooBarWidget** [comment]
Maybe there is a bug in the package script, but I can't tell what it is. Could you debug shared/package.sh? The `find_gems_containing_native_extensions` function is responsible for outputting the names of all native extension gems in the output directory.

**Comment by etdsoft** [comment]
```
$ make clean
$ make
$ ls output/lib/ruby/gems/2.1.0/extensions/
```
Is empty.

I see RedCloth and the others in the "Postprocessing build output...." stage:

https://gist.github.com/anonymous/7cdcef35db3afa16fb7e

**Comment by etdsoft** [comment]
@FooBarWidget any pointers I can follow?

**Comment by FooBarWidget** [comment]
That's very strange. This requires some debugging, maybe on your end. When the build script is done, output/lib/ruby/gems/2.1.0/extensions/ should be non-empty. There are two possibilities. Either during the clean step in the build script we remove too much stuff, or something else went wrong for an as yet unknown reason.

Can you run `cd output && find .` and paste the output to a gist so that I can inspect it? Can you also try to debug the build script?

**Comment by etdsoft** [comment]
https://gist.github.com/anonymous/171d8804f73e29605bf3

**Comment by etdsoft** [comment]
I tried to reproduce from a fresh start:

```
$ git clone https://github.com/phusion/traveling-ruby
$ cd traveling-ruby/osx/
$ make
$ ls output/lib/ruby/gems/2.1.0/extensions/
```

And again, empty.

This time I didn't run `make clean` at all. And I'd expect the other gems in there (nokogiri, sqlite, etc.) to be compiled somewhere.

This is the last part of the output:

https://gist.github.com/anonymous/a376738396973edd0733

Any tips on where to go from there?

**Comment by FooBarWidget** [comment]
Could you insert some 'ls' commands in the build script and check, in different parts in the script, whether the extensions directory is non-empty? It *should* be non-empty right after running 'bundle install'. If so, then we know that the cleaning commands that are run later have cleaned too much. If not, then we know something went wrong while running Bundler.

**Comment by etdsoft** [comment]
The `ls`s didn't help, it was empty. But I've found the problem, I had a `~/.bundle/config`:
```
---
BUNDLE_PATH: vendor/bundle
```
Which I suppose it was superseding the stuff in the script, maybe worth setting BUNDLE_PATH in the script?

That seems to have done the trick.

**Comment by FooBarWidget** [comment]
Yes. Maybe it's a good idea if the script explicitly checks whether there is no ~/.bundle/config in order to prevent problems like this.
