### ISSUE TITLE
EventMachine 1.0.7

### ISSUE THREAD

**Issue by ianks** [phusion/traveling-ruby#36]
Can you add EventMachine 1.0.7? Need it now for octodown.

https://github.com/ianks/octodown/pull/67

**Comment by FooBarWidget** [comment]
Will put it on the todo list.

**Comment by FooBarWidget** [comment]
Wait a minute, we already package 1.0.6. Can't you use that?

**Comment by ianks** [comment]
Fair enough. Looks like faye-websocket only relies on ~> 1.0.4 so that should work.
