### ISSUE TITLE
Seems to be an issue if there is a space anywhere in the file path of the directory

### ISSUE THREAD

**Issue by danmanstx** [phusion/traveling-ruby#38]
so running `./hello-1.0.0-osx/hello` works

but changing the directory with 

`mv hello-1.0.0-osx hello\ 1.0.0-osx` 

and running 

`./hello\ 1.0.0-osx/hello`

causes 

`/Users/danmanstx/Desktop/ruby/traveling-ruby-hello-demo/hello 1.0.0-osx/lib/ruby/bin/ruby: line 14: 1.0.0-osx/lib/ruby/lib/ruby/gems/2.1.0: No such file or directory`

I am really running into this when using a packaged ruby inside of something that resides in Application Support on Mac OS X. Above is just a simplified example.

**Comment by FooBarWidget** [comment]
It looks like it's caused by the fact that we set RUBYOPT in order to require a file. This filename contains a space, which borks the Ruby command line options parser.

One solution is to put restore_environment.rb in the standard Ruby load path so that we don't have to reference the full filename.

**Comment by danmanstx** [comment]
I've tried some different things, but can't seem to get anything working. What is the best way to do that @FooBarWidget? and Thanks so much for your help and this awesome project! 🍻

**Comment by FooBarWidget** [comment]
Move restore_environment.rb to lib/ruby/lib/2.1.0/. Then change the RUBYOPT option in lib/ruby/bin/ruby_environment to -rrestore_environment (without the full path).

**Comment by danmanstx** [comment]
Thanks @FooBarWidget moving `restore_enviroment.rb` to `lib/ruby/lib/2.1.0/`

and then changing `lib/ruby/bin/ruby_environment`  from 

```bash
echo RUBYOPT=\"-r$ROOT/lib/restore_environment\"
echo GEM_HOME="$ROOT/lib/ruby/gems/2.1.0"
echo GEM_PATH="$ROOT/lib/ruby/gems/2.1.0"
```
to

```bash
echo RUBYOPT="-rrestore_environment"
echo GEM_HOME=\"$ROOT/lib/ruby/gems/2.1.0\"
echo GEM_PATH=\"$ROOT/lib/ruby/gems/2.1.0\"
```

worked 👍

**Comment by ezekg** [comment]
Are there any disadvantages to doing this? If not, why don't we make this a default? This is especially problematic when you bundle a Ruby for a OSX app, as those are very likely to contain spaces.

**Comment by FooBarWidget** [comment]
It's simply because I haven't had time yet.
