### ISSUE TITLE
Idea: Build system should be written in Go

### ISSUE THREAD

**Issue by samdunne** [phusion/traveling-ruby#43]
This would enable the build system to be bundled as a binary that would work across windows/linux/osx.

I'd be willing to give this a go if someone thought it was a good idea.

**Comment by FooBarWidget** [comment]
No, that would not help. The build system consists of more than just a task runner. Specific SDKs, libraries and runtimes are required in order to build Traveling Ruby. If anything, we need VMs, but neither OS X nor Windows can be easily virtualized because of licensing restrictions.
