### ISSUE TITLE
Support for snappy gem with native extensions

### ISSUE THREAD

**Issue by sczizzo** [phusion/traveling-ruby#44]
Working on packaging an application that depends on the [snappy](https://github.com/miyucy/snappy) gem, which includes native extensions; it'd be great to get official support.

**Comment by FooBarWidget** [comment]
I think I can do that. Looks sane enough. But I'm currently preoccupied with various Passenger maintenance tasks. The earliest I can spend time on Traveling Ruby again is in a few weeks.

**Comment by sczizzo** [comment]
No worries. Just wondering, do you all have any resources on compiling my own extensions for Traveling Ruby? I understand it's not necessarily straightforward, but I think I could take a stab at it.

**Comment by FooBarWidget** [comment]
You add your gem to a Gemfile under 'shared/gemfiles/', then you run the build scripts.

But that's the easy part. The hard part is:

1. Figuring out whether your gem needs any libraries.
2. If so, how to compile them into static libraries with specific flags (-fPIC -fvisibility=hidden).
3. Figuring out how to statically link your gem to that library.
4. Make this work on both OS X and Linux.

**Comment by FooBarWidget** [comment]
Sorry for the delay. Passenger maintenance took much more time than I expected (RPM packaging is hell, learning SELinux too). I'm devoting some time to Traveling Ruby this week.

**Comment by FooBarWidget** [comment]
I need to fix a few things first, but I'm blocked by https://bitbucket.org/ged/ruby-pg/issue/219/please-release-a-new-gem

**Comment by FooBarWidget** [comment]
The gem has been packaged for OS X. I'll work on Linux next.

**Comment by FooBarWidget** [comment]
Linux version implemented.

**Comment by FooBarWidget** [comment]
Version 20150517 is released now and includes the snappy gem.
