### ISSUE TITLE
Native extensions support for Windows

### ISSUE THREAD

**Issue by bootstraponline** [phusion/traveling-ruby#46]
> Native extensions support for Windows. We're currently blocked by the fact that the RubyInstaller project hasn't been updated for Ruby 2.2.0 yet.

Now that [RubyInstaller 2.2.1](http://rubyinstaller.org/news/2015/03/06/rubyinstaller-2-2-1-released/) is released, does that unblock native extensions on Windows?

**Comment by FooBarWidget** [comment]
I will take a look when I have time.

**Comment by georf** [comment]
This would be nice :+1:

**Comment by miguelsan** [comment]
2.2.2 is there: http://rubyinstaller.org/news/2015/04/16/rubyinstaller-2-0-0-p645-2-1-6-and-2-2-2-released/

**Comment by georf** [comment]
Do you have an idea, how to do this work?

I developing a rails app for a friend and i told him, he can use it with windows. But i have no idea from placing rails on windows without installing. Or is there a other suiteable way to do this?

**Comment by FooBarWidget** [comment]
I haven't tested with a full Rails app yet, though some people have had success. You can only package your Rails app for Windows with Traveling Ruby if your app does not use any native extensions at all. So no Nokogiri, or any servers besides WEBrick.

**Comment by georf** [comment]
I only want to use sqlite for an quick and simple database solution. My
app will only be used in local network and so i dont need a real server.

Am 23.04.2015 um 22:42 schrieb Hongli Lai:

**Comment by BernardGatt** [comment]
Any plans as to when an update will be available that supports native extensions on windows?

**Comment by FooBarWidget** [comment]
I plan to start investigating that some time this week or next week.

**Comment by georf** [comment]
Hello @FooBarWidget,
do you have success with your investigation? I tried it myself, but I failed. Everytime when I bundle in Linux the nativ extensions from windows didnt work after that.

**Comment by FooBarWidget** [comment]
I did some investigation, but ran out of time because the other feature requests for the last release took too much time. For now I am back at Passenger maintenance and development. I'll try again next time.

**Comment by patakijv** [comment]
Has there been windows native extensions support in previous releases of traveling ruby? If we roll back to an older version that uses an older version of ruby, will we gain support for windows native extensions?

**Comment by bootstraponline** [comment]
> Has there been windows native extensions support in previous releases of traveling ruby?

no

**Comment by patakijv** [comment]
@FooBarWidget, First off, great work with what you have created so far! We actually develop on osx and linux but have a ruby (no rails) app we want to deploy to customers that use windows. Traveling ruby, once the native extensions are available, seems very promising as a way for us to minimize the hassle of deploying a ruby app to a customer not familiar or already setup with a ruby environment. 

Once you are able to complete your investigation you mentioned above, how long do you anticipate it would take to produce a **nokogiri** native extensions for windows? Days, weeks, months? This gem is our current obstacle with exploring traveling ruby.

**Comment by FooBarWidget** [comment]
Days probably. The Nokogiri developers already supply Windows binaries. My planned strategy is to reuse the binaries that gem developers already supply.

**Comment by patakijv** [comment]
Do you, or can you, document the process you go through (with all possible variations to include when there exists binaries already or not) in creating a packaged native extension for a gem and make this available in your wiki for this project? Maybe as you go through the next one and use it as an example? It might help with getting additional contributors on board and advance the movement, especially with windows. A packaged gem developers guide for traveling ruby?

**Comment by FooBarWidget** [comment]
I can try, but literally every single native extension I have packaged so far required a custom procedure. To make a native extension work, it is necessary that the packager understands how compilers and linkers work, static vs dynamic linking, symbol loading, and other kinds of low-level stuff. That makes it hard for me to write a generic guide that people can follow. For example I literally spent 3 days figuring out how to package the ncurses gem. In the end I had to make changes in the build system to accomodate for that gem's unique situation.

**Comment by patakijv** [comment]
Have you made any progress on this?

**Comment by FooBarWidget** [comment]
No progress so far, sorry.

**Comment by dapicester** [comment]
Hi @FooBarWidget, I would like to help packaging windows native extensions (starting with the ones I need of course: sqlite3, json, eventmachine and thin).

Let me know, thanks!

**Comment by FooBarWidget** [comment]
Hi @dapicester, and thanks for offering to help.

The approach I have in mind is to write some kind of script that can automatically download the precompiled binaries already published by gem authors. These binaries will then packaged in tarballs, in directory structures similar to the ones for the Linux and OS X extension tarballs. Finally, documentation needs to be updated to reflect the fact that only certain Windows native extensions are supported.

Do you think you can do this? Do you need any more pointers? Unfortunately, due to my commitment to Passenger I have not been able to put time in Traveling Ruby at all lately. But if you have specific questions I'd be happy to answer.

**Comment by dapicester** [comment]
@FooBarWidget Well, I noticed too that some gems do provide precompiled win32 binaries but so far I haven't been able to use them on my windows box (for example I cannot have `sqlite3` working without compiling the native extension).

However, whenever I will have a bit more time I will continue trying. I will comment here when I will come up with something working.

**Comment by dapicester** [comment]
Hi @FooBarWidget, just a quick update on this. I have been able to compile and bundle `json`, `thin`, `eventmachine` and `sqlite3` gems for traveling-ruby version 201505167 with Ruby 2.1.6 on Windows. Basically I just packaged the native extension compiled with Ruby 2.1.6 (32bit).
I put the bundles on [a public folder on Dropbox](https://www.dropbox.com/sh/khiruysxbk0c9q4/AACkP_ly1aX4GHBLgNxU5XOva?dl=0).

> The approach I have in mind is to write some kind of script that can automatically download the precompiled binaries already published by gem authors.

Unfortunately, [sqlite3-ruby](https://github.com/sparklemotion/sqlite3-ruby) does not provide yet binaries for Ruby 2.2 and I have been unable to use their pre-built extension on Ruby 2.1. So I have built a statically linked version of libsqlite3 and then compiled the `sqlite3` native extension.

I have not automated the tasks yet, but the fact that I have succeeded in bundling few gems for windows is already good start.

**Comment by FooBarWidget** [comment]
Good to hear @dapicester! Last time I tried, I haven't been able to compile anything on Windows.

**Comment by FooBarWidget** [comment]
Maybe you can contribute to the binaries to the original authors?

**Comment by patakijv** [comment]
@dapicester, Great to see some movement here on this. What were the lessons learned? Any chance you can document and share notes about the steps you've taken?

Is anyone planning to or currently trying to tackle [nokogiri](https://rubygems.org/gems/nokogiri)? We would like to package an application that uses the [fog](https://rubygems.org/gems/fog)  gem and I think the most obvious native extension based gem dependency is nokogiri

@FooBarWidget, What sort of direction or pointers can you give regarding someone attempting to bundle nokogiri for windows for traveling-ruby?

**Comment by FooBarWidget** [comment]
@patakijv The basic idea is that, once you have a Nokogiri binary, you drop it into the subdirectory that RubyGems expects, and then packages up everything. This is a very simple concept and it is how the Linux and OS X versions work. The main difficulty lies in compilation; compiling anything on Windows is very error-prone and much more difficult than on Linux and OS X.

**Comment by patakijv** [comment]
@FooBarWidget, excuse my ignorance or naiveness  here but if you are able to "have a Nokogiri binary", does that imply that the compilation part that are you saying is complicated is already completed and if as your comment on Jun 2nd indicates "The Nokogiri developers already supply Windows binaries", does this mean there is no compilation part of the process required for a Windows Nokogiri gem? Just package it up and away we go?

**Comment by FooBarWidget** [comment]
Yes.

**Comment by patakijv** [comment]
Wonderful. I'll give it a whirl and see if anything explodes.

**Comment by dapicester** [comment]
> What were the lessons learned? Any chance you can document and share notes about the steps you've taken?

@patakijv I wrote everything I did [in my last comment](https://github.com/phusion/traveling-ruby/issues/46#issuecomment-140077183).

My intention is to try and automate the build process, but I can tell you that this is not high priority in my task lists.

Anyway I will keep you informed on progress, if any.

**Comment by rafaelcgo** [comment]
@dapicester Great!
I need the ffi gem as well.
You said "Basically I just packaged the native extension compiled with Ruby 2.1.6 (32bit)."

Should I get the code from https://github.com/ffi/ffi, then read https://github.com/ffi/ffi/blob/master/Rakefile
and run `rake gem:windows`

After this I need to pack the compiled version, right?

ps: One more think, on the rake file, the ruby version 2.1.6 is not specified. It means it won't build for 2.1.6?

**Comment by dapicester** [comment]
@rafaelcgo I a not familiar with the ffi gem. What I did was installing the gem (e.g. `gem install sqlite3`) and then packaging the compiled native extension (the `.so` files).

**Comment by prees1** [comment]
@patakijv I am about to attempt exactly what you are describing with nokogiri. Wondering how you made out? Any catches along the way?

If it works well we should be able to document the process here on traveling ruby for others. Even if its just for nokogiri to start.

**Comment by pezholio** [comment]
I'm keen to get Windows support sorted for one of my gems too (I only need ffi), but I don't have access to a Windows machine to build on. Did anyone have any joy?

**Comment by prees1** [comment]
I temporarily switched my windows packaging to use Jruby and [rawr](github.com/rawr/rawr).

**Comment by dapicester** [comment]
I also switched to JRuby and [warbler](https://github.com/jruby/warbler/) for packaging.

**Comment by pezholio** [comment]
Ah, nice. Warbler looks interesting, but I guess you still need your users to have Java installed, which is a bit of a pain.

**Comment by jjgh** [comment]
No news on this??? :(

**Comment by FloorD** [comment]
We're consolidating all Windows issues in one 'milestone' and will work on Windows support the coming few weeks.
