### ISSUE TITLE
Curses native extension?

### ISSUE THREAD

**Issue by iurifq** [phusion/traveling-ruby#47]
I'm having troubles packaging a CLI app built using Thor. I am using Curses to adapt to the user's terminal width. When I create the package in the system I want to use, it works fine. However, when I create a Linux package in OSX and then I try to run it on Linux, it doesn't find curses dynamic library.

```
.../lib/vendor/ruby/2.1.0/gems/curses-1.0.1/lib/curses.rb:1:in `require': cannot load such file -- curses.so (LoadError)
```

I didn't see any reference to Curses in the tutorials or in [the Traveling Ruby Amazon S3 bucket](http://traveling-ruby.s3-us-west-2.amazonaws.com/list.html). As from version 2.1.0 of Ruby curses is not part of the standard library, do I need to treat is as a native extension when creating the package with traveling ruby?

**Comment by FooBarWidget** [comment]
Yep, it has been moved to a gem: https://github.com/ruby/curses

**Comment by FooBarWidget** [comment]
Gem has been packaged. Will be part of the next release.

**Comment by FooBarWidget** [comment]
Version 20150517 is released now and includes the curses gem.

**Comment by iurifq** [comment]
Thanks, it's great to hear that! :+1:
