### ISSUE TITLE
There was an error in your Gemfile, and Bundler cannot continue.

### ISSUE THREAD

**Issue by spacekookie** [phusion/traveling-ruby#50]
I just tried to adopt traveling ruby for my existing project. I had to do some hacking to make it also include my .gemspec (which contains all the dependencies), a bin folder, change the wrapper script, etc.

But now I'm getting the error:

`There was an error in your Gemfile, and Bundler cannot continue.`

without any other reference.
My Gemfile, Gemfile.lock and name.gemspec are located in `lib/vendor`.

WHile trying to debug what the issue is I commented out the Gemfile and added a simple `puts` into it but nothing changed, even after deleting the .lock.

Can you maybe help me with this? Because I'm getting NO feedback whatsoever what the issue with my Gemfile is :( Thanks

**Comment by FloorD** [comment]
We're consolidating all issues concerning gems, bundler and gem support to work on it the next few weeks. Thank you for reporting this!
