### ISSUE TITLE
Windows tar.gz for 2.2.2

### ISSUE THREAD

**Issue by semmons99** [phusion/traveling-ruby#54]
rubyinstaller.org has released 2.2.2 (and 2.2.3). Any chance we could get a traveling-ruby-20150715-2.2.2-win32-x86.tar.gz package uploaded to the Amazon bucket?

Is there anyway I can help?

**Comment by FooBarWidget** [comment]
Looks like I forgot to upload the Windows packages for the last release. I've done that now.
