### ISSUE TITLE
Another approach to Windows packaging

### ISSUE THREAD

**Issue by zverok** [phusion/traveling-ruby#59]
_(Not an issue/feature request, just a suggestion, sorry if it is wrong place to communicate it.)_

On Windows, typical user is afraid of .bat files, and they are looking ugly (unfriendly black icon, mandatory "flashing" console when running from GUI).

When, several years ago, I've need to "seemlessly" run Ruby programs on Windows, I've invented the trick: customly compiled ruby.exe, which, on running, checks its filename, and finds `app/*.rb` with the same name and runs it. So, typical package looks like:

```
+-myapp.exe  <== it is just renamed ruby.exe, provided by Traveling Ruby
+-app/
  |
  +-myapp.rb
```

This way the package will look like "normal" Windows program.

PS: if this approach will be accepted, it is important to remember Ruby has _two_ executables on Windows: `ruby.exe` and `rubyw.exe` -- the latter doesn't require console STDOUT, which is handy for GUI programs or background-running ones.

**Comment by FooBarWidget** [comment]
Yes that is definitely a better approach. It's just not something I've spent time on making. The Windows support so far is kind of a minimum viable product.

Unfortunately I'm bogged down by other responsibilities at the moment, so for the time being I do not have any time for maintaining Traveling Ruby.

**Comment by FloorD** [comment]
@zverok We're consolidating all Windows issues in one 'milestone' and will work on Windows support the coming few weeks.
