### ISSUE TITLE
windows version supported?

### ISSUE THREAD

**Issue by prees1** [phusion/traveling-ruby#74]
What version does travelling ruby support for Windows?

This says 2.1.5:

> Traveling Ruby currently supports Ruby 2.1.5 and Ruby 2.2.0 for Linux and OS X. But for Windows, only Ruby 2.1.5 is supported. This is because the RubyInstaller project hasn't released Ruby 2.2.0 binaries yet.

But RubyInstaller has 2.2.1 here:
http://rubyinstaller.org/news/2015/03/06/rubyinstaller-2-2-1-released/

And the S3 bucket lists 2.2.2?
https://traveling-ruby.s3-us-west-2.amazonaws.com/list.html

Is the readme just outdated?

**Comment by ansonhoyt** [comment]
and as of May 25 they're up to [RubyInstaller 2.4](https://rubyinstaller.org/2017/05/25/rubyinstaller-2.4.1-1-released.html) for Windows

**Comment by FloorD** [comment]
@prees1 The README is afaik pretty accurate in that Traveling Ruby hasn't seen work in a bit. We're consolidating all Windows issues in one 'milestone' and will work on Windows support the coming few weeks.
