### ISSUE TITLE
download issue with wget and ssl

### ISSUE THREAD

**Issue by elionne** [phusion/traveling-ruby#82]
I tried to compile traveling-ruby but there is some errors when downloading cmake and openssl due to ssl problems.

The first error with cmake.org is caused because the wget version does not manage alternate domains name.

And the second is because (I think) openssl is too old. I get an "Unable to establish SSL connection" when try to download openssl lib.

How can I avoid temporaly these issues. I tried to use the option "--no-check-certificate" but this solve only the fiste issue.

**Comment by shmilycherish** [comment]
how did you use “-no-check-certificate" to solve the first problem, I met the problem too

**Comment by elionne** [comment]
I use this patch :

```diff
diff --git a/linux/internal/setup-runtime-inside-mock b/linux/internal/setup-runtime-inside-mock
index aba246e..84f940c 100755
--- a/linux/internal/setup-runtime-inside-mock
+++ b/linux/internal/setup-runtime-inside-mock
@@ -10,7 +10,7 @@ function download_and_extract()
        local regex='\.bz2$'
 
        run rm -f "$BASENAME"
-       run wget -O "$BASENAME" "$URL"
+       run wget --no-check-certificate -O "$BASENAME" "$URL"
        if [[ "$URL" =~ $regex ]]; then
                run tar xjf "$BASENAME"
        else
```
But I recently retest, and that solve completly the problem.

**Comment by FooBarWidget** [comment]
Wget SSL errors occurred because we used CentOS 5 as build environment, which doesn't support TLS SNI, and doesn't support many modern certificate authorities. We've since migrated to Holy Build Box 3, which is based on CentOS 7.
