### ISSUE TITLE
Win32-api giving issue  creating packages for Windows

### ISSUE THREAD

**Issue by vgarg231** [phusion/traveling-ruby#84]
I have written small script project on windows, I have three gems in my gem file

I am using Travelling ruby on ubuntu to create its package but in the rake task when script try to dowload the gems these three gems gives error because I think its window specific gems and look for some dependencies

I kept these gems with in the project and referenced  in gem file , The script created zip file well, but when I run that on windows the errors that the win32... gems not found

rake package:win32 outputs when it trey to fetch gems 

``` shell
Fetching gem metadata from http://rubygems.org/............
Fetching version metadata from http://rubygems.org/.
Resolving dependencies...
Using jmespath 1.3.1
Using ffi 1.9.14
Using mini_magick 4.3.6
Installing win32-api 1.4.8 (was 1.6.0) with native extensions
Using bundler 1.13.5
Using aws-sdk-core 2.6.10
Using rautomation 0.17.0
Using win32-clipboard 0.6.4
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/vishalgarg/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20161019-3963-1e9bkxl.rb extconf.rb
checking for strncpy_s()... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling win32/api.c
win32/api.c:2:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
make: *** [api.o] Error 1

make failed, exit code 2


```

**Comment by FloorD** [comment]
We're consolidating all Windows issues in one 'milestone' and will work on Windows support the coming few weeks.
