### ISSUE TITLE
Please add support for gtk3 gem

### ISSUE THREAD

**Issue by gkjpettet** [phusion/traveling-ruby#87]
I'm following your tutorials on how to package up a ruby script that depends on a gem with native extensions. I believe **gtk3** is one such gem. I don't see that gem listed on your Amazon S3 list. Could you add this or provide instructions for how I could compile it to include in the a package for Mac and Linux?

Thanks,

**Comment by FloorD** [comment]
We're combining issues into larger milestones. Thank you for reporting this issue.
