### ISSUE TITLE
Bumping bundler version 

### ISSUE THREAD

**Issue by fxfactorial** [phusion/traveling-ruby#89]
Can you bump bundler version up, 

Getting this error: 
```
   bundler (< 2.0.0, >= 1.12.0) x86-mingw32

  Current Bundler version:
    bundler (1.7.12)

This Gemfile requires a different version of Bundler.
```

**Comment by joeainsworth** [comment]
Anybody know of a way to package a more recent version of bundler? I'm having an issue where I'm trying to run Travelling Ruby on AWS Lambda but I keep getting an error thrown about the version of bundler being too old.

**Comment by FloorD** [comment]
We're combining issues into larger milestones. Thank you for reporting this issue.
