### ISSUE TITLE
What is the necessary work for getting Native extensions working with Windows? 

### ISSUE THREAD

**Issue by fxfactorial** [phusion/traveling-ruby#91]
As a starting step, I need to get the gem dependency `unf_ext` working with traveling ruby, what kind of things would I need to change. I can do the work, just would appreciate some guidance. Thanks.

**Comment by hanetzer** [comment]
I'm also interested in this, and being a bit skilled in cross-compilation from linux to windows via
mingw-w64, I believe I could be of help here. Are you guys fine with the idea of cross-compiled
native gems?

**Comment by FooBarWidget** [comment]
Sounds great to me if you can get it working reliably.

Sent from my Android phone.

Op 26 dec. 2017 17:45 schreef "hanetzer" <notifications@github.com>:

**Comment by hanetzer** [comment]
@FloorD sure. I'm pretty alright with mingw-w64 and ruby stuff, and am pretty good at wrangling
build systems.
