### ISSUE TITLE
EPEL5 offline

### ISSUE THREAD

**Issue by doertedev** [phusion/traveling-ruby#99]
When I start rake on linux (centos7 machine) then I get the following error: 

Start: yum update
ERROR: Command failed:
 # ['/usr/bin/yum', '--installroot', '/var/lib/mock/epel-5-x86_64-2.1.6-x86_64/root/', '--releasever', '5', 'install', 'buildsys-build']
Error: Cannot retrieve repository metadata (repomd.xml) for repository: core. Please verify its path and try again
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
 Eg. Invalid release/repo/arch combination/
removing mirrorlist with no valid mirrors: /var/lib/mock/epel-5-x86_64-2.1.6-x86_64/root/var/cache/yum/core/mirrorlist.txt

rake aborted!
Command failed with status (30): [./setup-runtime -a x86_64 -r 2.1.6 runtime...]
/home/instana/traveling-ruby/linux/Rakefile:67:in `block (3 levels) in <top (required)>'
/home/instana/.gem/ruby/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => package => package:2.1.6:x86_64 => traveling-ruby-20150715-2.1.6-linux-x86_64.tar.gz => output/2.1.6-x86_64/bin => runtime/2.1.6-x86_64/ok
(See full trace by running task with --trace)

When peeking into the yum conf that gets thrown in root, I see that there is a mirrorlist being used that got moved to archive servers. 

Can someone tell me how I can build otherwise?

**Comment by FooBarWidget** [comment]
I'm looking into fixing this issue now, as part of [the work to incorporate pull request 94](https://github.com/phusion/traveling-ruby/pull/94#issuecomment-756749195).

**Comment by FooBarWidget** [comment]
This has been fixed in 725f4978616.
